name: 'DeliverDishDocker'
services:
  deliver-products:
    build: ./deliver-products
    ports:
      - "8001:8001"
    environment:
      - SPRING_PRODUCT_MONGODB_URI=${SPRING_PRODUCT_MONGODB_URI}
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
