name: 'DeliverDishDocker'
services:
  deliver-products:
    build: ./deliver-products
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://admin:admin@springapp.g71fe.mongodb.net/MyApp?retryWrites=true&w=majority&appName=springApp
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
