name: Build and Test

on:
  push:
    branches:
      - '**'  # Runs for all branches
  pull_request:
    branches:
      - '**'  # Runs for all PRs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step to check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step to cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step to set execute permission for mvnw
    - name: Set execute permission for mvnw
      run: chmod +x ./mvnw

    # Step to set the Java version (Temurin 17)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step to run Maven build with environment variables from GitHub Secrets
    - name: Run Maven build
      run: ./mvnw -ntp verify
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64
        SPRING_DATA_MONGODB_URI: ${{ secrets.SPRING_DATA_MONGODB_URI }}  # Reference the secret
